# Container for starting a cli for build commands
# Usage: docker-compose -f build.yml run cli
cli:
  image: phase2/devtools-build
  entrypoint: [ "/init" ]
  working_dir: /var/www
  command: /bin/bash
  volumes:
    - .:/var/www/
  external_links:
    - nyc_drupal_db:db

# Container for running drush in the docroot.
# Usage: docker-compose -f build.yml run drush <command>
# Where <command> is a direct drush command like cache-rebuild
drush:
  image: phase2/devtools-build
  entrypoint: [ "/init", "drush"]
  working_dir: /var/www
  volumes:
    - .:/var/www/
  external_links:
    - nyc_drupal_db:db

# Container for running drupal console in the docroot.
# Usage: docker-compose -f build.yml run drupal <command>
# Where <command> is a direct drupal command like router:debug
drupal:
  image: phase2/devtools-build
  entrypoint: [ "/init", "drupal"]
  working_dir: /var/www
  volumes:
    - .:/var/www/
  external_links:
    - nyc_drupal_db:db
