# Container to run Apache/PHP
www:
  container_name: nyc_drupal_www
  image: phase2/apache24php70
  environment:
    # The DNSDOCK variables make this container
    # referenceable by www.nyc-drupal.vm
    # It is recommended that your DNSDOCK_NAME match your container name
    DNSDOCK_NAME: www
    DNSDOCK_IMAGE: nyc-drupal
    DOCROOT: /var/www
    # Change some core container settings
    PHP_MAX_EXECUTION_TIME: 45
    # These enable debug/profiling support
    PHP_XDEBUG: "true"
    PHP_XHPROF: "false"
  # Links become entries in /etc/hosts We can refer to the
  # database host as db instead of db.nyc-drupal.vm or IP address
  links:
    - db
  # These src:dest pairs get mapped into the container at the
  # dest path and override what was built into the image. Both
  # a directory and an individual file can be overridden.
  #
  # Relative src paths and absolute ones pointing inside your home
  # directory will pull in contents from your host machine.
  #
  # Paths using /data are persistent and shared within the docker
  # machine so they should be namespaced (the value of
  # $DNSDOCK_IMAGE) was used in this case to create a base of /data/d8
  volumes:
    - .:/var/www/
    - ./env/local/xdebug.ini.tmpl:/etc/confd/templates/xdebug.ini.tmpl
    - /data/nyc_drupal/files:/var/www/sites/default/files

# Container to run our database
db:
  container_name: nyc_drupal_db
  image: phase2/mariadb
  environment:
    DNSDOCK_NAME: db
    DNSDOCK_IMAGE: nyc-drupal
    MYSQL_DATABASE: nyc_drupal
    TERM: xterm
  volumes:
    - /data/nyc_drupal/mysql:/var/lib/mysql
